//
//  TalentModel.swift
//  ImperiumMaledictumCharacter
//
//  Created by User on 11.01.2025.
//

import Foundation
import SwiftData

@Model
class Talent {
    var name: String
    var talentDescription: String
    
    init(name: String, talentDescription: String = "") {
        self.name = name
        self.talentDescription = talentDescription
    }
}

// MARK: - Talent Definitions
struct TalentDefinitions {
    static let talents: [String: String] = [
        "Acute Sense": "One of your primary five senses is highly developed, allowing you to spot what others miss. You may make Perception Tests to detect normally imperceptible details with the associated sense, as dictated by the GM. This could include seeing a lone Servo-Skull at an incredible distance, detecting the presence of a near- odourless poison, hearing the breath of a motionless ganger hidden in the next room, reading printed text by touch, or knowing by taste alone that two ration packages come from different manufactorums.",
        "Adrenaline Acceleration": "You are capable of impressive bursts of speed when your life is on the line. Your speed is Fast when Fleeing (page 208) or being Pursued (page 204).",
        "Agile Attacks": "Requirements: Agility 45, 2 Advances in Melee\n\nSpeed and accuracy make your attacks more potent than powerful blows. You may use your Agility Bonus instead of your Strength Bonus when calculating damage for melee weapons with the Subtle Trait.",
        "Air of Authority": "Requirement: 2 Advances in Presence\n\nYou exude confidence and command, your mere presence influential to many. The first time you meet a group, you can make a Challenging (+0) Rapport Test. On a success, you gain +1 Influence with that group until the end of the mission.",
        "Ambidextrous": "You can use both hands equally well, and suffer no penalty for doing something with your 'off' hand. As a result, you may weild a one-handed melee weapon and a pistol at the same time without penalty to attacks with either.",
        "Applied Anatomy": "Requirement: 2 Advances in Medicae\n\nYour knowledge of physiology gives you a keen familiarity with injuries and how they are caused. Though that usually helps you treat them, it also aids your understanding of how to inflict them. When you inflict a Critical Hit or Critical Wound, you may increase its rolled severity by your Advances in the Medicae Skill.",
        "Artistic": "You have a natural talent for the arts. This Talent can be taken multiple times, each time choose one of the following:\n- Literature: +2 SL to any Test related to reading or writing, such as cataloguing a comprehensive and persuasive evidential case or recognizing which Imperial sagas are being referenced in an ingeniously coded message.\n- Painting: +2 SL to any Test related to painting or drawing, such as creating a sketch of a person of interest or identifying the artist of an Imperial fresco and that it is a forgery.\n- Music: +2 to any Test related to singing or performing music, such as leading a religious chorus or surmising which planet in a particular sub-sector someone is from based on the tunes they hum.\n- Theatre: +2 SL to any Test related to acting or performing, such as dramatically depicting a character or identifying whether someone is wearing a uniform that was not made for them.",
        "Attentive Assistant": "You are a dutiful assistant, rendering aid with efficiency and aplomb even when the activity would normally be outside your skillset. You can use the Help Action (page 208) to assist someone even if you do not have Advances in the Skill being Tested. Additionally, if you do have an Advance, they gain +1 SL on the Test.",
        "Blank": "Requirements: Can only be taken during Character Creation. You can never be a Psyker and a Blank.\n\nYou are a Psychic Blank, one of the extremely rare Soulless. Psychic nulls like you carry the Pariah Gene, which denies you a psychic connection to the warp. Without that link, you have no presence within the immaterium, rendering you anathema to nearby psykers and Daemons. You curtail access to the immaterium in your immediate area. Ordinary Humans find your presence disturbing, and may even suffer headaches or nausea from prolonged exposure to you.\nThis Talent includes the following effects:\n- You automatically win any Opposed Test to resist a Psychic Power. Your result is always a Success (+1 SL).\n- You cannot be detected through Psyniscience (page 93) alone.\n- You are immune to Daemonic Possession.\n- You make Fellowship Tests when interacting with any creature with a connection to the warp with Disadvantage (i.e. all non-Blank Humans).\n- Tests made to Manifest a psychic power that targets your Zone, an individual in your Zone, or made within Short Range of you suffer from Disadvantage.\n- Daemons treat the Zone you are in as a Minor Hazard (page 206).\n- Individuals connected to a psychic hive mind (such as Genestealer Cultists) that enter or start their turn in your Zone must make a Challenging (+0) Discipline (Composure) Test or be Stunned (page 358).",
        "Bone Breaker": "Requirement: 2 Advances in Medicae (Specialisation)\n\nYour medical training allows you to find faults in anatomy and exploit them with ease. As an Action, you can break the bone of a Restrained target that you have the relevant Medicae Specialisation for. Select a Hit Location. That Hit Location now has a Broken Bone (Minor) (page 216). If the Hit Location already has a Broken Bone (Minor), it now has a Broken Bone (Major) (page 216).",
        "Briber": "Requirement: 2 Advances in Intuition (People)\n\nYou have a natural instinct for who can be paid off, and how to manipulate them with an appropriate 'donation' of Solars. You have Advantage on all Intuition (People) Tests to gauge whether someone would be amenable to a bribe. Additionally, you decrease the cost of any bribe by 10% for every Advance in Rapport (Haggle) you have.",
        "Bulwark": "Requirement: 3 Advances in Reflexes\n\nYou are proficient in using a shield to deflect danger from multiple sources. When using a shield and taking the Defend Action, you may choose to Defend an additionl ally that is within Immediate Range, or choose to Defend both an ally within Immediate Range and the Zone you currently occupy.",
        "Burglar": "Requirements: 1 Advance in both Athletics and Stealth\n\nBreaking and entering comes naturally to you. You have Advantage on Tests related to breaking and entering a location, such as climbing the exterior of a building, quietly breaking windows, or unlocking doors or lockboxes",
        "Chirurgeon": "Requirement: 2 Advances in Medicae\n\nYou can use a Chirurgeon's Kit (see page 145) to perform surgery. You can perform Amputations (see page 217) and treat Critical Wounds that are beyond the skills of others. Additionally you gain Advantage when treating Critical Wounds in combat.",
        "Close Quarters Discipline": "Requirements: 2 Advances in both Discipline and Ranged\n\nCountless hours of practice, training, and drilling have taught you to focus on firing your weapon, even when you are mere inches from danger. An enemy within Immediate range of you does not impose Disadvantage on your Ranged Attacks.",
        "Combat Master": "Requirement: 2 Advances in Melee\n\nYour accumulated years of combat experience allow you to keep lesser fighters at bay. You can take this Talent multiple times. Each time you take this Talent, you count as one more person for the purposes of determining if one side outnumbers the other in combat.",
        "Condemn The Witch": "Requirements: Willpower 40, Psyker Talent\n\nSimply denying a psyker access to the warp isn't enough for you. You twist their power, redirecting it to sear their mind, punishing them for their sorcerous transgressions and unforgivable blasphemies.\nWhen you successfully use Deny the Witch (page 163) to prevent a psyker from manifesting a psychic power, that psyker suffers Wounds equal to the Warp Rating of the power they attempted to manifest.",
        "Contortionist": "You can bend and twist your body to escape restraints and squeeze into smaller places. You are capable of fitting into unusually small or cramped spaces, such as the narrow pipes of a manufactorum. Additionally you have Advantage on Tests to resist or end the Restrained Condition or a grapple (page 208).",
        "Counter Attack": "Requirement: 3 Advances in Melee\n\nConforming to the idiom that 'the best defence is offence', you respond to an incoming attack with a lightning-fast counterstrike of your own.\nIf you are the target of a melee attack and win the Opposed Melee Test (page 211), you can choose to deal Damage to your opponent as if you made the attack.\nYou may purchase this Talent multiple times. You may Counter Attack once per round for each time you have purchased this Talent.",
        "Coup De Grace": "Requirement: 3 Advances in Reflexes\n\nYou know how to deliver a crushing final blow when you are dominating a situation. If you have 2 or more Superiority, you can take 2 turns in a row, sacrificing your turn next round.",
        "Data Delver": "Requirement: 2 Advances in Logic (Investigation)\n\nYou are naturally in tune with the flow of data and recorded information, effortlessly able to navigate the often byzantine records of the Imperium. You have Advantage on Tests made to find or retrieve information from a document or archive (whether analog or digital). Additionally, you read text in half the time it would normally take.\nIf you take this Talent again, you have Advantage on any Test made to determine where, when, how, or by whom a piece of information was created.",
        "Deadeye": "Requirement: 1 Advance in Ranged\n\nWhen you take the time to line up a shot in a practised manner, the benefits of your training flourish.\nWhen you Aim (page 207) and make a Ranged Attack you gain +1 SL. If you purchase this Talent again, when you Aim you have Advantage on Tests to Target a Location (page 210).",
        "Dealmaker": "Requirements: 1 Advance in both Intuition (People) and Rapport (Haggle)\n\nYou are skilled in trading and know how to close a deal. During a negotiation you can make an Intuition (People) Test. If you succeed you gain the benefit of one of the following effects:\n- You learn what the target would accept as a bribe, be it an object, specific information, or an amount of Solars. Not everyone can be bribed.\n- You decrease the cost of anything you buy from the target by 10%.\n- You increase the cost of anything you sell to the target by 10%",
        "Demolition Specialist": "Requirements: 2 Advances in Ranged (Ordnance) or 2 Advances in Dexterity (Defuse)\n\nExplosives are your area of expertise, and you've proved yourself able to use them successfully without blowing yourself up. Over the course of an hour, you can make a Challenging (+0) Tech (Engineering) Test to remove the Unstable Trait from an explosive. The GM determines the Difficulty. Additionally, when preparing delayed explosives (page 134) you may increase the Damage of those explosives by your Intelligence Bonus.\nThis Talent can be taken an additionl time, if you do, each time you make an attack with a weapon with the Blast Trait you can aim it in such a way that it ignores one character it would otherwise damage or effect.",
        "Devoted Servant": "You are particularly talented at a form of honest toil. Select one of the options from the Devoted Servant Table. You gain Advantage on Tests related to your area of expertise.",
        "Directed Strikes": "Requirement: 3 Advances in Melee\n\nYou aim your weapons carefully in close combat, directing strikes to land where they can do the most harm. You do not have Disadvantage when you take the Target Location Action with a melee weapon.",
        "Dirty Fighting": "Requirement: 2 Advances in Melee (Brawling)\n\nYou are proficient in the art of foul play. When you deal damage with a melee attack, you can choose to inflict the Blinded or Deafened Condition. If you succeed by +3 SL or more, you can choose to inflict the Stunned Condition instead (see Conditions, page 357).",
        "Disarm": "Requirement: 2 Advances in Melee\n\nYou are able to disarm an opponent with a careful flick of the wrist or a well-aimed blow to the hand. When you make a melee attack against an opponent who is the same size or smaller than you, instead of dealing damage you can choose to disarm them. If you succeed, your opponent drops a held object, which flies into a random adjacent Zone (with further effects as determined by the GM). If you win by +2 SL, you can determine which Zone the object lands in; if you win by +4 SL, you can take the object if you have a free hand, plucking it from the air with a flourish.",
        "Disturbing Voice": "The way you speak is unsettling, and to some, frightening. You gain +2 SL to Presence (Interrogation) and (Intimidation) Tests when using your voice. You suffer a −2 SL penalty to Fellowship Tests against someone that is disturbed by your voice, as determined by the GM.",
        "Distracting": "Regardless of your usual personality, you know how to be particularly vexing by interrupting people with disruptive, irritating, or offensive outbursts that are extremely effective distractions.\nYou can use this Talent once per encounter to interrupt another individual making a Test, imposing Disadvantage on their Test. In combat, this Talent is used as a Reaction (page 199).\nIf you purchase this Talent again, you can choose to gain one of the following:\n- Centre of Attention: When you are within Immediate range of an individual that isn't your ally, you may choose to inflict Disadvantage on Tests that target makes which anyone other than you.\n- Stunning Interjection: Once per encounter when you use the Distraction Talent, your target is Stunned (Minor) until the end of their next Turn.",
        "Drilled": "Requirement: 1 Advance in Discipline\n\nYou've been trained to face down the innumerable dangers of the universe, especially if you are backed up by other trained warriors. You have Advantage on Tests to resist the Frightened Condition, and you gain +1 SL to Discipline Tests for every ally with the Drilled Talent in the same Zone as you.\nIf another member of your group has the Drilled Talent, you can both choose to purchase the Drilled Talent again to gain the following:\n- Kill Team: When you are in the same Zone as another member of your party with the Drilled Talent, you can choose to act immediately after them in Initiative and gain +1 SL to all Tests.",
        "Dual Wielder": "Requirements: Ambidexterous, 2 Advances in Melee (One-handed)\n\nYou have learned to wield two melee weapons at once. You do not suffer Disadvantage when attacking with two melee weapons at the same time. See Two-weapon Fighting on page 214 for more information.",
        "Duellist": "Requirement: 2 Advances in Melee (One-handed)\n\nYou're a fantastic fencer when engaging an opponent one-on-one in armed melee combat. You treat all One- handed melee weapons that do not have the Subtle Trait as having Defensive Trait.\nThis Talent can be taken multiple times, each time after the first, choose to gain one of the following:\n- Duellist Feint: When you successfully attack with a One-handed melee weapon, you can choose to deal no damage and instead impose Disadvantage on attacks the target makes against you until the end of your next Turn.\n- Duellist Guard: When you make an attack with a One-handed melee weapon, you can choose to make that attack with Disadvantage to simultaneously make the Dodge Action.",
        "Eidetic Memory": "You can recall things you've seen with incredible clarity and fidelity for much longer than most people. Once you see something, even briefly, you can recall an image of what you saw with virtually perfect accuracy. You do not need to make Tests to recall visual details about images you saw.",
        "Ever Vigilant": "Requirement: 2 Advances in Awareness\n\nYour senses are permanently engaged in a hunt for the enemies of the Emperor, to the extent that you sleep with one eye open. You gain +1 SL to Tests to detect hidden enemies, and you suffer no penalties from the Unconsious or Blinded Conditions while sleeping.\nAdditionally, whenever you leave a location that has an object of interest or clue that the group did not find or closely examine, the GM may make a secret Awareness Test on your behalf with a Difficulty they determine. If the Test is successful, the GM may reveal this clue to you.",
        "Exploit Vulnerability": "Requirement: 2 Advances in Intuition (People)\n\nYou are ruthless in your use of information on your opponents. If you spend time to Know Thy Foe (page 196) before combat, you may choose the Hit Location of your first successful attack.",
        "Extended Proprioception": "Requirement: 3 Advances in Pilot (Specialisation)\n\nYour sense of your body's spatial movement and location extends to encompass the entirety of a vessel when you are piloting it. For vessels of your chosen Specialisation you always know their size and position in relation to their surroundings, meaning you will always know if the vessel will be able to fit through a gap, or feel if anything is off with the ship, such as a malfunctioning auspex or sabotaged void shield generator. Additionally, you do not suffer Disadvantage from being Blinded when you make a Pilot Test with your chosen Specialisation, and count as two people for the purposes of piloting a vessel that requires multiple crew to operate.",
        "False Retreat": "Requirement: 3 Advances in Rapport (Deception)\n\nYou know how to use the confusion of battle to reposition yourself by feigning cowardice. As an Action, you can pretend to Flee (page 208). Reduce Superiority by 1 and remove yourself from the encounter. At the start of your next turn, you can choose any location within Long Range of your previous location. You are now in that location and hidden from your enemies. When — or indeed, if — you return to the Encounter, Superiority increases by 1.",
        "Faithful": "Prerequisites: You must be a member of the Adeptus Ministorum Faction, or have +2 Influence with the Adeptus Ministorum, and 2 Advances in Lore (Theology).\n\nYou are a true believer of the Imperial Cult, a pious and devout member of the state religion of the Imperium and worshipper of the God-Emperor. You are capable of manifesting your faith as a light in the darkness of the 41st Millennium. This power can be used to further His divine will, but if it is misused, the Emperor is sure to punish such treachery.\nOnce per session you may add your Willpower Bonus in SL when you are making a Test related to your faith. For example:\n- If you are interrogating a suspected heretic, you can invoke the burning judgement of the God-Emperor's gaze to gain SL equal to your Willpower Bonus on your Presence (Intimidation) Test.\n- If you are righteously striking down a foul xenos creature or a heretic, you can scream a benediction of the Emperor's fury to gain SL equal to your Willpower Bonus on your next attack.\n- If you are attempting to recall information or locate a particular sacred text, you can make a prayer to the Emperor for guidance to gain SL equal to your Willpower Bonus on your Lore (Theology) Test.",
        "Familiar Terrain": "You are so familiar with the particular environs of your upbringing that you can better find cover to protect yourself or disappear entirely. Choose an environment from the following list. Within that environment you have Advantage on Stealth Tests and gain +1 Armour from Cover (page 204) in addition to what that cover typically grants. You may take this Talent multiple times, choosing another type of terrain each time.\n- Agri: Farmed fields, slaughterhouses, and other locations dedicated to food or water production.\n- Feudal: Any Human civilisation that is not a hive city, on a Forge world, or on a Shrine World.\n- Forge: Manufactorums, Omnissian forge-shrines, and the streets of Forge Worlds.\n- Hive: Anywhere in a hive city, including the toxic sumps that often lie beneath.\n- Natural: Forests, mountains, grasslands, plains, and other natural biomes untouched by civilisation.\n- Shrine: Churches, cathedrals, tombs, and the streets of Shrine Worlds.\n- Warzone: Any location that is or was recently an active warzone, as well as military buildings and active encampments.\n- Wasteland: The irradiated wastelands beyond hive cities, tundras, deserts.\n- Voidship: Any void-faring vessel of Imperial design.",
        "Fated": "Requirement: Character creation only\n\nYou are innately lucky, enjoy the Emperor's grace, or perhaps have been chosen by the ruinous powers themselves for some great and terrible purpose. Regardless of the reason, you gain 1 point of Fate. You can only take this Talent once.",
        "Field Medicae": "Requirement: 2 Advances in Medicae\n\nThere typically isn't time to properly treat wounds during a crisis, but a savvy healer like yourself knows how to patch up wounds and render immediate first aid to save lives under pressure. When you make a Medicae Test to heal a character (page 219), the Difficulty can not be harder than Challenging (+0).",
        "Flagellant": "Your dedication to your faith is such that you have shed many of the concerns of your flesh. You are happy to endure as much pain as required in service to the Emperor, and may even come to see that suffering as a form of worship far more holy than even the most sweetly sung hymn or devout prayer.\nYou gain Advantage on any Test to resist the effects of pain or interrogation. Additionally, any time you suffer a Critical Wound you may make a Challenging (+0) Lore (Theology) Test. If you succeed, you may ignore the effects of that Critical Wound for a number of rounds equal to your Willpower Bonus. During this time your faith sustains your mortified flesh, allowing you to fight on where most others would have fallen. Once the duration of this effect is over, you suffer the full effects of the Critical Wound as normal.",
        "Flanking Fire": "Requirement: 2 Advances in Ranged\n\nYour ally's attacks can open up your enemy's defences, allowing you to better place your shots. When you make a ranged attack targetting an enemy target in the same Zone as one of your revealed allies, your attack can bypass some of their cover. If your target is in Cover they reduce the Armour benefit that Cover grants by 2.",
        "Flesh Is Weak": "Requirement: 2 Advances in Tech (Augmetics)\n\nThe Cult of the Omnissiah preaches that the flesh is inferior to the perfection of the machine, and you have fully internalised that teaching. The number of Augmetics (page 152) you can take is equal to double your Toughness Bonus.",
        "Forbidden Knowledge": "Requirement: Character creation, or with GM permission (see Forbidden Lore)\n\nThrough accident, proscribed research, or by order of your Patron, you have gained access to unsanctioned information. Each time you take this Talent, you gain access to one of the following Specialisations:\n- Linguistics (Forbidden)\n- Lore (Forbidden)\n- Medicae (Forbidden)",
        "Forger": "Requirements: 2 Advances in both Linguistics and Lore\n\nYou are capable of forging documentation that allows you to wield Influence over a specific Faction. The Faction you are trying to gain Influence over determines the type of Test you must make when attempting to create the forgery, which takes a full day. Some example factions are listed below, though the GM may allow other options.\n- Adeptus Administratum: Lore (Imperium)\n- Adeptus Ministorum: Lore (Theology)\n- The Inquisition: Lore (Cypher)\n- Rogue Trader Dynasty: Linguistics (High Gothic)\nThe difficulty of the Test determines how much Influence the forgery will give you:\n- Difficult (−10): +1 Influence\n- Hard (−20): +2 Influence\n- Very Hard (−30): +3 Influence\nWhen you make the Test to forge the document, keep track of your SL. Anyone who attempts to inspect the document to discern its veracity makes an Opposed Test of their Logic (Evaluation) against the SL of your original Test.",
        "Full-Auto Fanatic": "Requirement: 3 Advances in Ranged\n\nYou are a fearsome foe when you wield a weapon with a high rate of fire. If your weapon has the Rapid Fire Trait (page 125), you can choose to spend double the number of bullets required for its Rapid Fire Rating to target all individuals in the Zone with a single attack.",
        "Frenzy": "You can work yourself into a frothing battle rage. As a Free Action you can make a Challenging (+0) Willpower Test to enter a frenzied state. While frenzied your Strength Bonus increases by +1, you are immune to the Frightened Condition. On your turn, you must attempt to engage the nearest enemy in melee combat. You remain in this state until all enemies you can currently see have been defeated, or until you are affected by the Stunned or Unconscious Condition.\nThis Talent can be taken multiple times, each time choose one of the following:\n- Frenzied Control: You can make a Difficult (−10) Discipline (Composure) Test as an Action, to halt your Frenzied state.\n- Frenzied Fearlessness: Whenever you would become Frightened, you may immediately become Frenzied instead.\n- Frenzied Momentum: One per Turn, when you kill an enemy whilst Frenzied, you may immediately Move or take another Action.",
        "Gallows Humour": "Requirement: 2 Advances in Rapport (Charm)\n\nYou find humour in the darkest of places, and can use it to bolster the morale of your allies, keeping them alive in the direst of times. As an Action, you can use Charm (Rapport) to make a joke that can stabilise someone in a dire situation.\n- If your target is Fatigued or Frightened, you can make a Challenging (+0) Rapport (Charm) Test as an Action to remove the Condition.\n- If your target is Stunned, you can make a Challenging (+0) Rapport (Charm) Test as an Action to remove the Condition.\n- If your target is Dying, you can make a Challenging (+0) Rapport (Charm) Test. If you succeed, your target does not die at the end of the round, and instead can survive for another 1 + SL rounds.",
        "Gothic Gibberish": "Requirement: 1 Advance in Linguistics\n\nGothic Gibberish is the appropriately verbose name given to the practice of talking rapidly and incessantly to confound a target by burying them beneath a deluge of obscure information.\nYou can use Gothic Gibberish by making a Rapport (Charm) Test opposed by the target's Discipline (Composure). Your target must share at least one language with you, and neither of you can be in combat. If you win the Opposed Test, your target is Stunned for as long as you continue to spout nonsense. Creatures Stunned by your Gothic Gibberish may do nothing other than stare at you dumbfounded as they try to catch up with or understand what you are saying. They may attempt another Discipline (Composure) Test opposed by your Rapport (Charm) at the end of each of their Turns, or whenever the GM deems it fitting — even Gothic Gibberish can't hold someone's attention if a firefight breaks out nearby!",
        "Guardian": "Requirement: 3 Advances in Reflexes\n\nYou are quick enough to interpose yourself between your allies and harm. As a Free Action at the start of combat, choose one allied character within Medium Range. You are their guardian and are considered to be defending them (Defend, page 207). If the target is attacked and you are within Medium Range, you can immediately move to Defend them. If doing so causes you to break Engagement (page 212), your opponents have Disadvantage on their melee attack.",
        "Gunslinger": "Requirements: Ambidexterous, 2 Advances in Ranged (Pistols)\n\nYou have learned to wield two ranged weapons at once. You do not suffer Disadvantage when attacking with two ranged weapons at the same time. See Two-weapon Fighting on page 214 for more information.",
        "Hatred": "You wield your fury as a weapon. Choose the object of your hatred — for example, xenos, heretics, or gangers. Whenever you come into contact with the the subject of your hatred, you must make a Difficult (−10) Discipline (Composure) Test. If you fail the Test, you have Advantage on any Discipline (Fear) Tests and +1 SL to any attack Tests you make. Whilst overcome by this hate, you must immediately attempt to destroy the hated group by the fastest and most deadly means possible. You may attempt another Difficult (−10) Discipline (Composure) Test at the end of each of your turns to end this effect. Otherwise, the effect ends when you fall unconscious or all visible subjects of your hatred are dead.",
        "Hit And Run": "Requirement: 3 Advances in Reflexes (Acrobatics)\n\nWhen you strike an enemy, you can take advantage of their pain to acrobatically reposition yourself. As a Free Action, when you deal one or more Wounds you can make a Reflexes (Acrobatics) Test to Disengage and move to an adjacent Zone.",
        "Holdout Expert": "You are an expert at hiding small objects about your person — perhaps in a small compartment hidden in your clothing, or even in a hollow chamber inside an agumetic limb.\nYou can conceal one small item, no bigger than the palm of your hand. Anyone searching you must make a Hard (−20) Awareness (Touch), Dexterity (Pickpocket) or Logic (Investigation) Test to discover the hidden object. If the individual searching you employs any technology, such as an Auspex or a Cyber-hound, this difficulty is reduced to Challenging (+0).",
        "Hypno-Indoctrination": "Someone spent a great deal of time and effort hypnotically imparting you with specific training you could not consciously recall as it dwelt in your subconscious. Now it has revealed itself to you. Roll twice on the Random Talents Table (page 74). You now have those Talents. Hypno-Indoctrination can only be taken once.",
        "Icon Bearer": "Requirements: 1 Advance in Lore (Theology) and 1 Advance in Presence\n\nWhen you lift a holy icon aloft it sends your companions' hearts soaring. When you are holding a Holy Icon (page 148) any ally within Medium Range that can see you gains bonus benefits.",
        "Emperor's Aegis": "With the Gamemaster's permission, you can take the Condemn the Witch Talent without requiring the Psyker Talent. Rather than reflecting any personal control over the energies of the warp, you instead enjoy some limited protection from psychic powers that even a psyker would struggle to explain. You may attribute this to unwavering faith, typically in the Emperor, or perhaps the protection of other, less beneficent entities. Whatever the result, you feel an instinctive abhorrence for Psychic Powers and may attempt to Deny the Witch using your Discipline (Psychic) Skill.",
        "Ignorance Is My Shield": "Protection through lack of knowledge",
        "Inspiring Presence": "Motivating others in crisis",
        "Inheritor": "Noble birthright and training",
        "Lawbringer": "Authority and justice expertise",
        "Lickspittle": "Obsequious flattery skills",
        "Martyrdom": "Willingness to sacrifice for cause",
        "Medicae Maverick": "Unconventional medical techniques",
        "Mental Fortress": "Psychic resistance training",
        "Mimic": "Voice and mannerism imitation",
        "Overseer": "Management and supervision skills",
        "Pathologist": "Disease and death expertise",
        "Phlebotomist": "Blood and bodily fluid knowledge",
        "Porter": "Enhanced carrying capacity",
        "Psychic Castigation": "Mental attack techniques",
        "Psychic Flood": "Overwhelming psychic assault",
        "Psyker": "Warp-touched abilities",
        "Quickdraw": "Lightning-fast weapon deployment",
        "Rapid Reload": "Fast ammunition replacement",
        "Read Lips": "Understanding speech without hearing",
        "Registered Trader": "Commercial licensing and connections",
        "Sanctioned Psyker": "Official psychic training",
        "Secret Identity": "Maintaining false personas",
        "Shock Assault": "Overwhelming first strike",
        "Skulker": "Stealth and hiding expertise",
        "Slippery": "Escape and evasion skills",
        "Superior Commander": "Advanced leadership training",
        "Suppressing Fire": "Area denial shooting",
        "Sure-Footed": "Balance and terrain navigation",
        "Tactical Movement": "Combat positioning expertise",
        "Tenacious": "Stubborn determination",
        "Two-Handed Cleave": "Heavy weapon techniques",
        "Unflinching Presence": "Intimidating demeanor",
        "Unremarkable": "Ability to blend into crowds",
        "Void Legs": "Adaptation to zero gravity",
        "Well-Prepared": "Thorough planning and preparation"
    ]
    
    static let allTalents = Array(talents.keys).sorted()
}
